name: Install Package

on:
  repository_dispatch:
    types: [install_package]

jobs:
  install-package:
    runs-on: self-hosted
    steps:
    - name: Validate Package Input
      env:
        PACKAGE_NAME: ${{ github.event.client_payload.package }}
      run: |
        if [ -z "$PACKAGE_NAME" ]; then
          echo "Error: No se especificó ningún paquete para instalar"
          exit 1
        fi

    - name: Update Package Lists
      run: sudo apt update

    - name: Install Specified Package
      env:
        PACKAGE_NAME: ${{ github.event.client_payload.package }}
      run: |
        echo "Instalando paquete: $PACKAGE_NAME"
        sudo apt-get install -y "$PACKAGE_NAME"

    - name: Verify Package Installation
      env:
        PACKAGE_NAME: ${{ github.event.client_payload.package }}
      run: |
        if dpkg -s "$PACKAGE_NAME" &> /dev/null; then
          echo "Paquete $PACKAGE_NAME instalado correctamente"
        else
          echo "Error: No se pudo instalar $PACKAGE_NAME"
          exit 1
